### ISSUE TITLE
Review CORS support for amplify.request

### ISSUE THREAD

**Issue by jdsharp** [mikehostetler/amplify#20]
https://github.com/cityindex/amplify/tree/master/request/CORS

**Comment by mrdavidlaing** [comment]
Let me know if you'd like me to package files in a different place before submitting a patch (I don't really understand how your build process works)

**Comment by jdsharp** [comment]
Hey David,

Will do, our build process is an internal tool that we'll be releasing shortly, but it's not quite finished being baked yet.

Cheers,
- Jonathan

**Comment by mrdavidlaing** [comment]
Bump - any update on this?

**Comment by scottgonzalez** [comment]
Thanks, but this seems out of scope. There really shouldn't be a CORS type, this should be built into the ajax type. If there's a change that needs to be made in amplify.request in order to allow you to build a plugin that does that, let us know. We're very interested in allowing reasonable extensions.

It's unfortunate that CORS is a mess, but I don't want to ship code in amplify that relies on browser plugins such as Flash. Also, since this uses jQuery's ajax transports, it won't work with all of the versions of jQuery that we support.

**Comment by mrdavidlaing** [comment]
Hi Scott,

In my case, I have to support CORS requests on IE7, and the only way I can
see to do this is using a Flash transport.

If you could expose a way to override the XHR that is being used; then
perhaps this plugin could be more "low level"

What do you think?

David

2011/9/9 Scott González <
reply@reply.github.com>

> Thanks, but this seems out of scope. There really shouldn't be a CORS type,
> this should be built into the ajax type. If there's a change that needs to
> be made in amplify.request in order to allow you to build a plugin that does
> that, let us know. We're very interested in allowing reasonable extensions.
> 
> It's unfortunate that CORS is a mess, but I don't want to ship code in
> amplify that relies on browser plugins such as Flash. Also, since this uses
> jQuery's ajax transports, it won't work with all of the versions of jQuery
> that we support.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/appendto/amplify/issues/20#issuecomment-2051746

## 

David Laing
Open source @ City Index - github.com/cityindex
http://davidlaing.com
Twitter: @davidlaing

**Comment by scottgonzalez** [comment]
jQuery already provides jQuery.ajaxSettings.xhr.

2011/9/9 David Laing <
reply@reply.github.com>
