### ISSUE TITLE
';' missing in minified version

### ISSUE THREAD

**Issue by jd4u** [mikehostetler/amplify#49]
The min version of amplified must have ';' at the end of the script.
i.e. (function(a,b){......}(amplify,jQuery);

While combining multiple js files, error is raised in subsequent script module.

I suggest to modify the build to add colon at the end as well as at the start of the script. At the start of the script will help reduce any other script's similar issue.

**Comment by molokoloco** [comment]
First of all, thanks for your nice code. 

To says.. i'm running some trouble after a closure compiler pass http://closure-compiler.appspot.com/home
Strange because 2 or 3 times each 10 times, it say me "no object "store" in amplify while i was using it long time after window.load ... something in your main declaration of the object ? Well resolved by a "space only" minification..

**Comment by scottgonzalez** [comment]
This is fixed with the use of grunt in 77dd4250552746b0437b252c062169f86d0697d6.
