### ISSUE TITLE
Access sender/current request in decoder

### ISSUE THREAD

**Issue by eirikhm** [mikehostetler/amplify#62]
I'd like to have access to the invoked request/resource in a decoder. As far as I can tell this is currently not supported, but should be easy to implement. Passing request, settings and ajaxSettings to decoder() probably.

Any chance for this happening?

**Comment by scottgonzalez** [comment]
What's the use case?

On Tue, Jun 5, 2012 at 3:39 AM, Eirik Hoem <
reply@reply.github.com

**Comment by scottgonzalez** [comment]
This was discussed in IRC. The use case really calls for creating a new request type, not providing request details to the decoder.

**Comment by steve-heine** [comment]
I'm working with a REST endpoint and don't have control the format of the response data. (its not my library). The response structure is similar for all calls, but the names of the objects depend on the resource.
JSend wont work for me so I planned on creating a custom decorder. Since each response has its own response object names. I was planning on defining this in the request definition, and then access that value in the decoder. Is this possible?
